/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_appsync_graphqlEndpoint": "https://bcgc2vfyorf63emiaqftapb3bm.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lmlpwi7pbzbx7lewls22vbbtua",
    "aws_cognito_identity_pool_id": "eu-west-3:e28644ee-8bd9-4e07-9d28-3a501cb6cc91",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_AWueDuABv",
    "aws_user_pools_web_client_id": "75jpk7se0ioqrcmna68vps9hqn",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
